# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(823, 596)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(-170, -50, 1241, 681))
        self.background.setStyleSheet("background-color:black;")
        self.background.setObjectName("background")
        self.iron = QtWidgets.QLabel(Form)
        self.iron.setGeometry(QtCore.QRect(350, 20, 471, 291))
        self.iron.setText("")
        self.iron.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\iron.jpg"))
        self.iron.setScaledContents(True)
        self.iron.setObjectName("iron")
        self.voice = QtWidgets.QLabel(Form)
        self.voice.setGeometry(QtCore.QRect(0, 30, 411, 311))
        self.voice.setText("")
        self.voice.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\Aqua.gif"))
        self.voice.setScaledContents(True)
        self.voice.setObjectName("voice")
        self.start = QtWidgets.QLabel(Form)
        self.start.setGeometry(QtCore.QRect(640, 430, 151, 71))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\Start.png"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.quit = QtWidgets.QLabel(Form)
        self.quit.setGeometry(QtCore.QRect(640, 510, 151, 61))
        self.quit.setText("")
        self.quit.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\Quit.png"))
        self.quit.setScaledContents(True)
        self.quit.setObjectName("quit")
        self.date = QtWidgets.QLabel(Form)
        self.date.setGeometry(QtCore.QRect(40, 400, 171, 71))
        self.date.setText("")
        self.date.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\td.jpg"))
        self.date.setScaledContents(True)
        self.date.setObjectName("date")
        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(40, 500, 171, 71))
        self.time.setText("")
        self.time.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\td.jpg"))
        self.time.setScaledContents(True)
        self.time.setObjectName("time")
        self.earth = QtWidgets.QLabel(Form)
        self.earth.setGeometry(QtCore.QRect(310, 390, 231, 181))
        self.earth.setText("")
        self.earth.setPixmap(QtGui.QPixmap("C:\\Users\\ASHOK\\Documents\\ASHOK\\Projects\\AI [Desktop Voice Assistant]\\Model-2\\GUI\\Earth.gif"))
        self.earth.setScaledContents(True)
        self.earth.setObjectName("earth")
        self.datetextBrowser = QtWidgets.QTextBrowser(Form)
        self.datetextBrowser.setGeometry(QtCore.QRect(52, 419, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.datetextBrowser.setFont(font)
        self.datetextBrowser.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;\n"
"")
        self.datetextBrowser.setObjectName("datetextBrowser")
        self.timetextBrowser = QtWidgets.QTextBrowser(Form)
        self.timetextBrowser.setGeometry(QtCore.QRect(55, 518, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.timetextBrowser.setFont(font)
        self.timetextBrowser.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:white;\n"
"border-radius:none;\n"
"")
        self.timetextBrowser.setObjectName("timetextBrowser")
        self.startpushButton = QtWidgets.QPushButton(Form)
        self.startpushButton.setGeometry(QtCore.QRect(650, 440, 131, 51))
        self.startpushButton.setStyleSheet("background-color:transparent;")
        self.startpushButton.setText("")
        self.startpushButton.setObjectName("startpushButton")
        self.quitpushButton = QtWidgets.QPushButton(Form)
        self.quitpushButton.setGeometry(QtCore.QRect(650, 510, 131, 51))
        self.quitpushButton.setStyleSheet("background-color:transparent;")
        self.quitpushButton.setText("")
        self.quitpushButton.setObjectName("quitpushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.background.setText(_translate("Form", "TextLabel"))
        self.datetextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Date: 05-12-24</span></p></body></html>"))
        self.timetextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Nirmala UI\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Time: 08:30:11</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
